### ISSUE TITLE
Can't select new department

### ISSUE THREAD

**Issue by jrodal98** [SyllabiShare/syllabi-share#3]
If you select department A, you cannot select another department until you deselect department A. Imo, it would be more intuitive if you could simply select the next department you wish to view, which may happen if a user is looking up multiple course syllabi.

![selection_bug](https://user-images.githubusercontent.com/35352333/82721664-66f6e600-9c8d-11ea-9701-20af19cd529a.gif)

**Comment by verndrade** [comment]
so that was by design as a temp workaround. The html would render weirdly if multiple depts were opened. I plan to fix that, but its low pri atm. The workaround is found in the <script> tags in index.html where if the paypal link is hidden (it gets hidden when opening a dept) then another dept wont open until the first dept is selected if anyone wants to address it
